---
abstract: unknown
author:
  - unknown
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.98, CPAN::Meta::Converter version 2.142060'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Cache-Cache
no_index:
  directory:
    - t
    - inc
requires:
  Digest::SHA1: '2.02'
  Error: '0.15'
  File::Spec: '0.82'
  IPC::ShareLite: '0.09'
  Storable: '1.014'
version: '1.07'
